###

GET http://localhost:3000/api/products?page=1

###

PATCH http://localhost:3000/api/update-stock
Content-Type: application/json

{
    "sku": "SKU-1001",
    "newStock": 95
}

###

POST http://localhost:3000/api/create-product
Content-Type: application/json

{
    "name": "BlackBerry",
    "sku": "SKU-1003",
    "price": 30000,
    "stock": 200
}



###

GET http://localhost:3000/api/orders

###

POST http://localhost:3000/api/create-order
Content-Type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "sku": "SKU-1001",
    "quantity": 5
}