###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Diksha",
    "email": "diksha@gmail.com",
    "password": "Diksh@123",
    "phone": "6203319626"
}


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "yash@gmail.com",
    "password": "yash@123"
}

###

GET http://localhost:3000/api/auth/me

### 

POST http://localhost:3000/api/auth/logout