###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Nitish",
    "email": "nitish@gmail.com",
    "password": "N!t!sh020",
    "phone": "1234567899"
}


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "nitish@gmail.com",
    "password": "N!t!sh020"
}

### 

POST http://localhost:3000/api/auth/logout